version: '3'
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./index.html:/usr/share/nginx/html/index.html
        container_name: nginx-starter
